# fly.toml app configuration file generated for bot-ds on 2024-12-27T00:22:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bot-ds"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  http_checks = []  # You might want to define health checks here if necessary
  tcp_checks = []   # Same as above, define checks if needed

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
